### PR TITLE
kamal-kaur04

### PR DESCRIPTION
**Pull request by kamal-kaur04**
I have implemented Rock, Paper, and Scissors in this pull request as raised in issue #1 

- [x] I have read the Code Of Conduct.
- [x] I have followed all the steps of submission properly.

### CODE REVIEW

**Comment by yashpaneliya** [comment]
Hello contributor👋,

As we all know that Hacktoberfest-2020 is ended. Hope you enjoyed it a lot and made some awesome contributions. 
So now it's time for schwags🎁🤩

**Send your email (linked with your GitHub account) in the reply of this comment. Mention any one of the maintainers (@yashpaneliya @rudrabarad @harshptl14 @chirayu-joshi @dhruvpatel1706 ) in the reply.**

**We'll send a form on the email you'll provide. Please reply ASAP.**

Join [Club Gamma Discord](https://discord.com/invite/kjnp6wU) for future updates.

**Comment by yashpaneliya** [comment]
Hello contributor👋,

As we all know that Hacktoberfest-2020 is ended. Hope you enjoyed it a lot and made some awesome contributions. 
So now it's time for schwags🎁🤩

**Send your email (linked with your GitHub account) in the reply of this comment. Mention any one of the maintainers (@yashpaneliya @rudrabarad @harshptl14 @chirayu-joshi @dhruvpatel1706 ) in the reply.**

**We'll send a form on the email you'll provide. Please reply ASAP.**

Join [Club Gamma Discord](https://discord.com/invite/kjnp6wU) for future updates.

**Comment by kamal-kaur04** [comment]
> Hello contributorwave,
> 
> As we all know that Hacktoberfest-2020 is ended. Hope you enjoyed it a lot and made some awesome contributions.
> So now it's time for schwagsgiftstar_struck
> 
> **Send your email (linked with your GitHub account) in the reply of this comment. Mention any one of the maintainers (@yashpaneliya @rudrabarad @harshptl14 @chirayu-joshi @dhruvpatel1706 ) in the reply.**
> 
> **We'll send a form on the email you'll provide. Please reply ASAP.**
> 
> Join [Club Gamma Discord](https://discord.com/invite/kjnp6wU) for future updates.

Hello @yashpaneliya ,
My Email Address linked with GitHub account is [kmlkaur73@gmail.com](mailto:kmlkaur73@gmail.com).

Thank you

**Comment by VeteraNovis** [comment]
Could anyone look at merging my PR?  It's the final PR I need for Hacktoberfest!  Thanks Club Gamma

**Pull request merged**
